import { DM_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import PageTransition from "@/components/PageTransition";
import DotPattern from "@/components/magicui/dot-pattern";
import clsx from "clsx";
import { cn } from "@/lib/utils";
import { PrismicPreview } from "@prismicio/next";
import { createClient, repositoryName } from "@/prismicio";

const dmSans = DM_Sans({
  subsets: ["latin"],
  display: 'swap',
  variable: '--font-dm-sans',
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={clsx(dmSans.variable, "relative min-h-screen")}>
      <DotPattern className={cn(
          "[mask-image:radial-gradient(2000px_circle_at_center,white,transparent)]",
        )} />
        <Header />
        <PageTransition>{children}</PageTransition>
        <Footer />
      </body>
      <PrismicPreview repositoryName={repositoryName} />
    </html>
  );
}
